#Tensor!

In [15]:
import tensorflow as tf
import numpy as np

##Constructors
A tensor is an N-dimensional array of data. They behave like numpy n-dimension except that:

<li>tf.constant produces constant tensors
<li>tf.Variable produces tensor that can be modifies

In [2]:
# A scalar is a tensor type with 0 dimension
x = tf.constant(3) # Shape: ()

# A vector is a tensor type with 1 dimension
x = tf.constant([3, 5, 7]) # Shape: (3,)

# A matrix is a tensor type with 2 dimensions
x = tf.constant([[3, 5, 7], [4, 6, 8]]) # Shape: (2,3)

# A 3D tensor has 3 dimensions
x = tf.constant([[[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [10, 11, 12]]]) # Shape: (2, 2, 3)

# An n-d tensor has n dimensions
x1 = tf.constant([2, 3, 4]) # Shape: (3,)
x2 = tf.stack([x1, x1]) # Shape: (2,3)
x3 = tf.stack([x2, x2, x2, x2]) # Shape: (4,2,3)
x4 = tf.stack([x3, x3]) # Shape: (2,4,2,3)

In [5]:
# Tensor can be sliced
x = tf.constant([
    [3, 5, 7],
    [4, 6, 8]
]) # Shape: (2,3)
y = x[:,1] # Shape: (2,)
print(y)

tf.Tensor([5 6], shape=(2,), dtype=int32)


In [6]:
# Tensor can be reshaped
x = tf.constant([
    [3, 5, 7],
    [4, 6, 8]
]) # Shape: (2,3)
y = tf.reshape(x, [3,2]) # Shape: (3,2)
print(y)

tf.Tensor(
[[3 5]
 [7 4]
 [6 8]], shape=(3, 2), dtype=int32)


A Variable is a tensor whose value can be changes.

The variable constructor requires an initial value for the variable, which can be a tensor of any shape and type. These initial values define the type and the shape of the variable. After construction, the type and the shape of the variable are fixed.

In [7]:
x = tf.Variable(2.0, dtype=tf.float32, name='my_var') # Shape: (), x -> 2.0
print(x)

<tf.Variable 'my_var:0' shape=() dtype=float32, numpy=2.0>


The value of the Variable can be modified

In [8]:
x.assign(45.8) # x -> 45.8
print(x)

<tf.Variable 'my_var:0' shape=() dtype=float32, numpy=45.8>


In [9]:
x.assign_add(4) # x -> x + 4
print(x)

<tf.Variable 'my_var:0' shape=() dtype=float32, numpy=49.8>


In [10]:
x.assign_sub(3) # x -> x - 3
print(x)

<tf.Variable 'my_var:0' shape=() dtype=float32, numpy=46.8>


tf.Variable will typically hold model weights that need to be updated in a training loop

In [14]:
# Linear regression: y = w*X
w = tf.Variable([[1.], [2.]])
X = tf.constant([[3., 4.]])
tf.matmul(w, X)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

##Tensor Operations

You can convert a tensor to a NumPy array either using `np.array` or the `tensor.numpy` method:



In [16]:
x = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float16)
np.array(x)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [17]:
x.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

You can do basic math on tensors, including addition, element-wise multiplication, and matrix multiplication.

In [21]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2], dtype=tf.int32)`

In [19]:
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [20]:
tf.multiply(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [22]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

In [23]:
# Element-wise addition
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [24]:
# Element-wise multiplication
a * b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [25]:
# Matrix multiplication
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

Other types of operations

In [27]:
x = tf.constant([[4.0, 5.0], [10.0, 1.0]])

In [28]:
# Find the largest value
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [30]:
# Find the index of the largest value
tf.math.argmax(x)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

In [31]:
# Compute the soft argmax
tf.nn.softmax(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>